version: '2'

services:
  nginx:
    image: openresty-with-debug:latest
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./data:/data
    ports:
      - "8080:8080"
